src/main/java/org/genesys2/server/model/impl/User.java
/**
 * Copyright 2014 Global Crop Diversity Trust
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

package org.genesys2.server.model.impl;

import java.beans.Transient;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Cacheable;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.sf.oval.constraint.Email;
import net.sf.oval.constraint.NotEmpty;
import net.sf.oval.constraint.NotNull;

import org.genesys2.server.model.BusinessModel;
import org.genesys2.server.model.UserRole;
import org.genesys2.server.servlet.controller.rest.serialization.UserSerializer;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@Cacheable
@Entity
@Table(name = "\"user\"")
@JsonSerialize(using = UserSerializer.class)
public class User extends BusinessModel {

	
	private static final long serialVersionUID = 4564013753931115445L;

	@Column(length = 36, unique = true)
	private String uuid;

	// validation
	@NotNull(message = "sample.error.not.null")
	@NotEmpty(message = "sample.error.not.empty")
	@Email(message = "sample.error.wrong.email")
	// hibernate
	@Column(name = "email", nullable = false, unique = true)
	private String email;

	// validation
	@NotNull(message = "sample.error.not.null")
	@NotEmpty(message = "sample.error.not.empty")
	// hibernate
	@Column(name = "password", nullable = false)
	private String password;

	// validation
	@NotNull(message = "sample.error.not.null")
	@NotEmpty(message = "sample.error.not.empty")
	// hibernate
	@Column(name = "name", nullable = false)
	private String name;

	@Enumerated(EnumType.STRING)
	@Column(name = "loginType", length=10, nullable=false, columnDefinition="VARCHAR(10) DEFAULT 'PASSWORD'")
	private LoginType loginType = LoginType.PASSWORD;

	// validation
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	@ElementCollection
	@Enumerated(EnumType.STRING)
	@CollectionTable(name = "user_role", joinColumns = @JoinColumn(name = "user_id"))
	@Column(name = "user_role")
	private Set<UserRole> roles = new HashSet<UserRole>();

	/**
	 * System accounts cannot log in through web or otherwise.
	 */
	@Column(nullable = false, updatable = false, name = "sys")
	private boolean systemAccount = false;

	@Column
	private boolean enabled = true;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable = true)
	private Date lockedUntil;

	@PrePersist
	void ensureUUID() {
		if (this.uuid == null) {
			this.uuid = UUID.nameUUIDFromBytes(email.getBytes()).toString();
		}
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public LoginType getLoginType() {
		return loginType;
	}

	public void setLoginType(LoginType loginType) {
		this.loginType = loginType;
	}

	public Set<UserRole> getRoles() {
		return roles;
	}

	public void setRoles(Set<UserRole> roles) {
		this.roles = roles;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof User)) {
			return false;
		}

		final User user = (User) o;

		if (email != null ? !email.equals(user.email) : user.email != null) {
			return false;
		}
		if (name != null ? !name.equals(user.name) : user.name != null) {
			return false;
		}
		if (password != null ? !password.equals(user.password) : user.password != null) {
			return false;
		}
		if (roles != null ? !roles.equals(user.roles) : user.roles != null) {
			return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		int result = email != null ? email.hashCode() : 0;
		result = 31 * result + (password != null ? password.hashCode() : 0);
		result = 31 * result + (name != null ? name.hashCode() : 0);
		result = 31 * result + (roles != null ? roles.hashCode() : 0);
		return result;
	}

	@Override
	public String toString() {
		return "User id=" + id + " email=" + email;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public void setSystemAccount(boolean systemAccount) {
		this.systemAccount = systemAccount;
	}

	public boolean isSystemAccount() {
		return systemAccount;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getLockedUntil() {
		return this.lockedUntil;
	}

	public void setLockedUntil(Date lockedUntil) {
		this.lockedUntil = lockedUntil;
	}

	@Transient
	public boolean isAccountLocked() {
		return this.lockedUntil != null && this.lockedUntil.after(new Date());
	}

	@Transient
	public boolean isAccountExpired() {
		// We don't support account expiration
		return false;
	}

	@Transient
	public boolean isPasswordExpired() {
		// We don't support password expiration
		return false;
	}

	public boolean hasRole(String roleName) {
		for (final UserRole userRole : getRoles()) {
			if (userRole.getName().equalsIgnoreCase(roleName)) {
				return true;
			}
		}
		return false;
	}

}

src/main/java/org/genesys2/server/servlet/controller/ProfileController.java
/**
 * Copyright 2014 Global Crop Diversity Trust
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

package org.genesys2.server.servlet.controller;

import java.util.List;

import org.genesys2.server.model.oauth.OAuthClientDetails;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

public abstract class ProfileController<T, ID> extends BaseController {

	private final String viewPrefix = getViewPrefix();

	/**
	 * Get details record for T with given identifier
	 *
	 * @param identifier
	 * @return
	 */
	protected abstract T getDetails(ID identifier);

	/**
	 * Return list of T entries to display on index page.
	 *
	 * Example: "/admin/oauth"
	 *
	 * @return
	 */
	protected abstract List<OAuthClientDetails> list();

	/**
	 * Get prefix to JSP views
	 *
	 * @return
	 */
	protected abstract String getViewPrefix();

	/**
	 * List controllers
	 *
	 * @return
	 */
	@RequestMapping(value = "")
	public String index(ModelMap model) {
		model.addAttribute("items", list());
		return viewPrefix + "/index";
	}

	/**
	 * View client details
	 *
	 * @param model
	 * @param clientId
	 * @return
	 */
	@RequestMapping(value = "/{id}")
	public final String details(ModelMap model, @PathVariable("id") ID identifier) {
		final T item = getDetails(identifier);

		if (item == null) {
			_logger.warn("No such item " + identifier);
			return "redirect:/admin/oauth/" + identifier + "/edit";
		}

		model.addAttribute("item", item);
		return viewPrefix + "/details";
	}

	/**
	 * Overridable method to add extra items to the profile
	 *
	 * @param item
	 */
	public void addDetails(ModelMap model, T item) {
		// NOOP
	}

	/**
	 * Edit client details
	 *
	 * @param model
	 * @param clientId
	 * @return
	 */
	@RequestMapping(value = "/{id}/edit")
	public String edit(ModelMap model, @PathVariable("id") ID identifier) {
		final T item = getDetails(identifier);

		if (item == null) {
			return viewPrefix + "/edit";
		}

		model.addAttribute("item", item);
		return viewPrefix + "/edit";
	}

	/**
	 * Edit client details
	 *
	 * @param model
	 * @param clientId
	 * @return
	 */
	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public String update(ModelMap model, @RequestParam(required = false, defaultValue = "", value = "id") ID identifier) {
		final T item = getDetails(identifier);

		if (item == null) {

			return viewPrefix + "/edit";
		}

		model.addAttribute("client", item);
		return "redirect:.";
	}
}

src/main/java/org/genesys2/server/servlet/controller/rest/UserController.java
/**
 * Copyright 2014 Global Crop Diversity Trust
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

package org.genesys2.server.servlet.controller.rest;

import java.util.List;

import net.sf.oval.ConstraintViolation;
import net.sf.oval.Validator;
import net.sf.oval.constraint.MinLength;
import net.sf.oval.constraint.NotBlank;
import net.sf.oval.constraint.NotNull;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.genesys2.server.ServiceEndpoints;
import org.genesys2.server.exception.AuthorizationException;
import org.genesys2.server.model.impl.User;
import org.genesys2.server.service.InstituteService;
import org.genesys2.server.service.TeamService;
import org.genesys2.server.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.http.MediaType;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@PreAuthorize("isAuthenticated()")
@RequestMapping(value = { "/api/v0", "/json/v0" })
public class UserController extends RestController {
	private static final Log LOG = LogFactory.getLog(UserController.class);

	@Autowired
	protected UserService userService;

	@Autowired
	protected TeamService teamService;

	@Autowired
	protected InstituteService instituteService;

	/**
	 * Returns logged in user's profile
	 *
	 * @return - user's profile
	 */
	@RequestMapping(value = ServiceEndpoints.ME, method = RequestMethod.GET, produces = { MediaType.APPLICATION_JSON_VALUE })
	public @ResponseBody
	Object getProfile() throws AuthorizationException {
		final User user = userService.getMe();
		return OAuth2Cleanup.clean(user);
	}

	@RequestMapping(value = "/me/institutes", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody
	Object listInstitutes() {
		return instituteService.listMyInstitutes(new Sort("code"));
	}

	@RequestMapping(value = "/me/teams", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody
	Object listTeams() {
		return teamService.listMyTeams();
	}

	@RequestMapping(value = "/me/teams", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	@PreAuthorize("hasRole('VETTEDUSER')")
	public @ResponseBody
	Object createTeam(@RequestBody TeamJson teamJson) {
		final Validator validator = new Validator();
		final List<ConstraintViolation> violations = validator.validate(teamJson);
		if (violations.size() > 0) {
			// TODO We could do better messages on validation error
			throw new ModelValidationException("Validation error", violations);
		}
		LOG.info("Creating team " + teamJson);
		return OAuth2Cleanup.clean(teamService.addTeam(teamJson.name));
	}

	@PreAuthorize("hasRole('ADMINISTRATOR')")
	@RequestMapping(value = "/user/{uuid}/locked", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody
	boolean changeLock(@PathVariable("uuid") String uuid, @RequestBody boolean locked) {
		userService.setAccountLock(uuid, locked);
		return true;
	}

	@PreAuthorize("hasRole('ADMINISTRATOR')")
	@RequestMapping(value = "/user/{uuid}/enabled", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody
	boolean changeEnabled(@PathVariable("uuid") String uuid, @RequestBody boolean enabled) {
		userService.setAccountEnabled(uuid, enabled);
		return true;
	}

	@RequestMapping(value = "/me/teams/{teamId}/leave", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody
	Object leaveTeam(@PathVariable("teamId") Long teamId) {
		LOG.info("Leaving team " + teamId);
		teamService.removeMe(teamId);
		return JSON_OK;
	}

	public static class TeamJson {
		@NotBlank
		@NotNull
		@MinLength(value = 4)
		public String name;
	}
}

src/main/webapp/WEB-INF/jsp/admin/users/edit.jsp
<!DOCTYPE html>

<%@ include file="/WEB-INF/jsp/init.jsp" %>

<html>
<head>
<title><spring:message code="userprofile.update.title" /></title>
</head>
<body>
	<!-- Any errors? -->
	<gui:alert type="danger" display="${not empty emailError}">
		<c:out value="${emailError}" />
	</gui:alert>

	<form role="form" class="form-horizontal validate" action="<c:url value="/admin/users/${user.uuid}/update" />" method="post">
		<div class="form-group">
			<label for="name" class="col-lg-2 control-label"><spring:message code="registration.full-name" /></label>
			<div class="col-lg-3">
				<input type="text" id="name" name="name" class="span3 form-control" value="${user.name}" />
			</div>
		</div>
		<div class="form-group">
			<label for="email" class="col-lg-2 control-label"><spring:message code="registration.email" /></label>
			<div class="col-lg-3">
				<input type="text" id="email" name="email" class="span3 form-control" value="${user.email}" />
			</div>
		</div>

		<c:if test="${user.loginType eq 'PASSWORD'}">
			<div class="form-group">
				<label for="currentPassword" class="col-lg-2 control-label"><spring:message code="registration.current-password" /></label>
				<div class="col-lg-3">
					<input type="password" id="currentPassword" name="currentPwd" class="span3 form-control" autocomplete="off" />
				</div>
			</div>
			<div class="form-group">
				<label for="password" class="col-lg-2 control-label"><spring:message code="registration.password" /></label>
				<div class="col-lg-3">
					<input type="password" id="password" name="pwd1" class="span3 form-control" autocomplete="off" />
				</div>
			</div>
			<div class="form-group">
				<label for="confirm_password" class="col-lg-2 control-label"><spring:message code="registration.confirm-password" /></label>
				<div class="col-lg-3">
					<input type="password" id="confirm_password" name="pwd2" class="span3 required form-control" autocomplete="off" equalTo="#pwd1" />
				</div>
			</div>
		</c:if>

		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<input type="submit" value="<spring:message code="save"/>" class="btn btn-primary" />
				<a class="btn btn-default" href="<c:url value="/admin/users/${user.uuid}" />" class="btn"> <spring:message code="cancel" />
				</a>
			</div>
		</div>
        <!-- CSRF protection -->
        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
	</form>
	
	<security:authorize access="hasRole('ADMINISTRATOR')">
	<h1>
		<spring:message code="user.roles" />
	</h1>
	<form role="form" class="form-horizontal validate" action="<c:url value="/profile/${user.uuid}/update-roles" />" method="post">
        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
		<c:forEach items="${availableRoles}" var="role">
		<div class="form-group">
			<div class="col-lg-12">
				<label><input type="checkbox" name="role" value="<c:out value="${role}" />" ${user.hasRole(role) ? 'checked="true"' : ''} /><c:out value="${role}" /></label>
			</div>
		</div>
		</c:forEach>
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<input type="submit" value="<spring:message code="save"/>" class="btn btn-primary" />
			</div>
		</div>
	</form>
	</security:authorize>
</body>
</html>

src/main/webapp/WEB-INF/jsp/admin/users/index.jsp
<!DOCTYPE html>

<%@ include file="/WEB-INF/jsp/init.jsp" %>

<html>
<head>
<title><spring:message code="user.page.list.title" /></title>
</head>
<body>
	<table class="table table-striped">
		<thead>
			<tr>
				<th class="col-xs-5"><spring:message code="registration.full-name" /></th>
				<th class="col-xs-2"> 1</th>
				<th class="col-xs-5"><spring:message code="registration.email" /></th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${pagedData.content}" var="user" varStatus="status">
				<tr>
					<td class="col-xs-5"><c:if test="${not user.systemAccount}">
							<a href="<c:url value="/admin/users/${user.uuid}" />"><c:out
									value="${user.name}" /></a>
						</c:if></td>
					<td class="col-xs-2"><c:if test="${user.systemAccount}">SYSTEM</c:if>
						<c:if test="${not user.enabled}">DISABLED</c:if> <c:if
							test="${user.accountLocked}">LOCKED</c:if></td>
					<td class="col-xs-5"><c:out value="${user.email}" /></td>
				</tr>
			</c:forEach>
		</tbody>
	</table>

	<local:paginate2 page="${pagedData}" />
</body>
</html>

src/main/webapp/WEB-INF/jsp/admin/users/profile.jsp
<!DOCTYPE html>

<%@ include file="/WEB-INF/jsp/init.jsp" %>

<html>
<head>
<title><spring:message code="userprofile.page.title" /></title>
</head>
<body>
	<security:authorize access="hasRole('ADMINISTRATOR') || (isAuthenticated() && principal.user.id == #user.id)">
		<a href="<c:url value="/admin/users/${user.uuid}/edit" />" class="close"> <spring:message code="edit" /></a>
	</security:authorize>

	<div class="form-horizontal">
		<div class="form-group">
			<label for="password" class="col-lg-2 control-label"><spring:message code="user.full-name" /></label>
			<div class="col-lg-5 form-control-static"><c:out value="${user.name}" /></div>
		</div>

		<security:authorize access="hasRole('ADMINISTRATOR') || (isAuthenticated() && principal.user.id == #user.id)">
			<div class="form-group">
				<label for="password" class="col-lg-2 control-label"><spring:message code="user.email" /></label>
				<div class="col-lg-5 form-control-static"><c:out value="${user.email}" /></div>
			</div>

			<div class="form-group">
				<label class="col-lg-2 control-label"><spring:message code="user.account-status" /></label>
				<div class="col-lg-5 form-control-static">
					<c:if test="${user.systemAccount}">SYSTEM</c:if>
					<c:if test="${not user.enabled}"><spring:message code="user.account-disabled" /></c:if>
					<c:if test="${user.accountLocked}"><spring:message code="user.account-locked-until" />
						<fmt:formatDate value="${user.lockedUntil}" type="time" />
					</c:if>
				</div>
			</div>

			<div class="form-group">
				<label class="col-lg-2 control-label"><spring:message code="user.roles" /></label>
				<div class="col-lg-10 form-control-static">
					<c:forEach items="${user.roles}" var="role">
						<div><c:out value="${role}" /></div>
					</c:forEach>
				</div>
			</div>

		</security:authorize>


	</div>


	<security:authorize access="hasRole('ADMINISTRATOR')">
		<div class="form-group">
			<button class="btn btn-default" id="acccount-lock">Lock</button>
			<button class="btn btn-default" id="acccount-unlock">Unlock</button>

			<button class="btn btn-default" id="acccount-disable">Disable</button>
			<button class="btn btn-default" id="acccount-enable">Enable</button>
		</div>
	</security:authorize>

	<div class="form-group">
                <security:authorize access="hasRole('ADMINISTRATOR') || (isAuthenticated() && principal.user.id == #user.id)">
                    <a href="<c:url value="/management/user/${user.uuid}/tokens" />" class="btn btn-default"><spring:message code="oauth-client.issued.tokens" /></a>
                </security:authorize>
                <security:authorize access="hasRole('ADMINISTRATOR') || principal.user.id == #user.id">
                	<c:if test="${not user.hasRole('VALIDATEDUSER')}">
                    <a href="<c:url value="/admin/users/${user.uuid}/send"/>"  class="btn btn-default"/>Send validation email</a>
                    </c:if>
                </security:authorize>
                <security:authorize access="hasRole('ADMINISTRATOR')">
                	<c:if test="${not user.hasRole('VETTEDUSER')}">
					<a href="<c:url value="/admin/users/${user.uuid}/vetted-user"/> "class="btn btn-default"/>Vetted user</a>
					</c:if>
                </security:authorize>
    </div>

	<h3><spring:message code="team.user-teams" /></h3>

	<ul class="funny-list">
	<c:forEach items="${teams}" var="team" varStatus="status">
		<li class="${status.count % 2 == 0 ? 'even' : 'odd'}"><a href="<c:url value="/team/${team.uuid}" />"><c:out value="${team.name}" /></a>

			<security:authorize access="isAuthenticated() && principal.user.id == #user.id">
			<a x-team-id="${team.id}" class="pull-right"><spring:message code="team.leave-team" /></a>
			</security:authorize>
		</li>
	</c:forEach>
	</ul>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>
    <!--End modal-->
	<security:authorize access="isAuthenticated() && principal.user.id == #user.id">
	<h4><spring:message code="team.create-new-team" /></h4>
	<form id="new-team-form" class="form-horizontal">
		<div class="form-group">
			<label for="team-name" class="col-lg-2 control-label"><spring:message code="team.team-name" /></label>
			<div class="col-lg-3"><input type="text" name="name" id="team-name" class="span3 form-control" /></div>
			<div class="col-lg-1">
				<input type="submit" value="<spring:message code="create" />" class="btn btn-primary" />
			</div>
		</div>
	</form>
	</security:authorize>

<content tag="javascript">
	<security:authorize access="isAuthenticated()">
	<script src="<c:url value="/html/js/main.js" />"></script>
	<script src="<c:url value="/html/js/jsonclient.js" />"></script>
	<script type="text/javascript">
	jQuery(document).ready(function() {



	<security:authorize access="principal.user.id == #user.id">
		$("#new-team-form input[type=submit]").on("click", function(e) {
			e.preventDefault();
			x01("<c:url value="/json/v0/me/teams" />", { success: function(e) {
				window.location.reload();
			}}, $(this.form).serializeObject());
		});

		$("a[x-team-id]").on("click", function(e) {
			e.preventDefault();
			x01("<c:url value="/json/v0/me/teams/" />" + $(this).attr('x-team-id') + "/leave",
					{ success: function(e) {
						window.location.reload();
					}});
		});
	</security:authorize>

	<security:authorize access="hasRole('ADMINISTRATOR')">
		$("button#acccount-enable").on("click", function(e) {
			e.preventDefault();
			x01("<c:url value="/json/v0/user/${user.uuid}/enabled" />", { success: function(e) {
				window.location.reload();
			}}, true);
		});
		$("button#acccount-disable").on("click", function(e) {
			e.preventDefault();
			x01("<c:url value="/json/v0/user/${user.uuid}/enabled" />", { success: function(e) {
				window.location.reload();
			}}, false);
		});
		$("button#acccount-lock").on("click", function(e) {
			e.preventDefault();
			x01("<c:url value="/json/v0/user/${user.uuid}/locked" />", { success: function(e) {
				window.location.reload();
			}}, true);
		});
		$("button#acccount-unlock").on("click", function(e) {
			e.preventDefault();
			x01("<c:url value="/json/v0/user/${user.uuid}/locked" />", { success: function(e) {
				window.location.reload();
			}}, false);
		});
	</security:authorize>
	});
	</script>
	</security:authorize>
</content>
</body>
</html>